// Fake 'autogenerated' config declarations for the sdk code.

#pragma once

#define PICO_NO_BINARY_INFO 1
#define PICO_NO_RAM_VECTOR_TABLE 1
#define __STRING(x) #x

#ifndef __always_inline
#define __always_inline __attribute__((always_inline))
#endif 

#ifndef __noinline
#define __noinline __attribute__((noinline))
#endif
